name: ci

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Go test
        run: go test ./...

      - name: Go build
        run: go build ./cmd/nifi-flow-upgrade
